services:
  jupyterlab:
    image: jupyterdocker
    env_file: 
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./:/contrans2025
    
  postgres:
    image: postgres
    env_file: 
      - .env
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/18/docker

volumes:
  postgres_data:
  
# networks:

